global:
 resolve_timeout: 1m
 slack_api_url: 'https://hooks.slack.com/services/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'

route:
 receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerting'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: "[{{ .Status | toUpper }}] {{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
    text: |-
          {{ range .Alerts }}*Description:* {{ .Annotations.description }}
          *Namespace:* {{ .Annotations.Namespace }}
          *Pod:* {{ .Annotations.Pod }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
